<?php

namespace AppBundle\Repository;

/**
 * orchardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orchardRepository extends \Doctrine\ORM\EntityRepository
{
}
